/* eslint-disable */
/**
 * Generated API stubs -- this file is auto-generated by `bunx convex dev`.
 * It will be replaced when you run `bunx convex dev` or `bunx convex deploy`.
 *
 * For now, this placeholder enables imports from "convex/_generated/api"
 * to resolve without errors during development.
 */

// Create a deep proxy that returns itself for any property access
// so that api.organizations.listForUser, api.sync.runCustomers, etc. all resolve
function createDeepProxy(): any {
	return new Proxy(function () {}, {
		get(_target, _prop) {
			return createDeepProxy();
		},
		apply() {
			return undefined;
		},
	});
}

const api: any = createDeepProxy();
const internal: any = createDeepProxy();

export { api, internal };
