/* eslint-disable */
/**
 * Generated server stubs -- this file is auto-generated by `bunx convex dev`.
 * It will be replaced when you run `bunx convex dev` or `bunx convex deploy`.
 *
 * For now, this placeholder enables imports from "convex/_generated/server"
 * to resolve without errors during development.
 */

import {
	queryGeneric,
	mutationGeneric,
	actionGeneric,
	internalQueryGeneric,
	internalMutationGeneric,
	internalActionGeneric,
	httpActionGeneric,
} from "convex/server";

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const action = actionGeneric;
export const internalQuery = internalQueryGeneric;
export const internalMutation = internalMutationGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;

// biome-ignore lint/suspicious/noExplicitAny: placeholder
export type DataModel = any;
// biome-ignore lint/suspicious/noExplicitAny: placeholder
export type Doc<T extends string> = any;
// biome-ignore lint/suspicious/noExplicitAny: placeholder
export type Id<T extends string> = any;
